# Beginning of
## ***Numpy Library***


In [1]:
import numpy as ny

In [2]:
myArr = ny.array([[1,4,5,22,46,7]])

In [3]:
myArr

array([[ 1,  4,  5, 22, 46,  7]])

In [4]:
myArr[0]

array([ 1,  4,  5, 22, 46,  7])

In [5]:
myArr[0,2]

5

In [6]:
myArr.shape

(1, 6)

In [7]:
myArr.dtype

dtype('int32')

In [ ]:
myArr

In [8]:
myArr[0,3] = 33

In [9]:
myArr

array([[ 1,  4,  5, 33, 46,  7]])

#### Array Creation methods

###### these are the Array Creation using Python objects

In [10]:
listArrays = ny.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
listArrays

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
listArrays.dtype 

dtype('int32')

In [13]:
listArrays.shape  

(3, 3)

In [14]:
listArrays.size

9

##### now deal with dictionary datatypes

In [15]:
dictArray = ny.array({"Name":"Dipesh","Age":25,"Age":26})

In [16]:
dictArray

array({'Name': 'Dipesh', 'Age': 26}, dtype=object)

##### arange(range give you array) , ones, zeros(give you array of zeros)

In [17]:
zeros = ny.zeros([2,3], ny.int32)

In [18]:
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
zeros.shape

(2, 3)

In [ ]:
arrange = ny.arange(15) # here you can get float steps.

In [21]:
arrange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
ones = ny.ones([2,3,3])

In [23]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [24]:
lspace = ny.linspace(1,6,4)

In [25]:
lspace

array([1.        , 2.66666667, 4.33333333, 6.        ])

In [26]:
emp = ny.empty((4,6)) #gives you random int elements of array

In [27]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56577399e-307, 2.22523004e-307, 1.29062229e-306],
       [1.69121367e-306, 8.45603440e-307, 1.33511290e-306,
        2.00262080e-307, 1.60220393e-306, 5.56295627e-307],
       [3.33774490e-307, 1.89145198e-307, 2.22522189e-306,
        6.23060744e-307, 6.23053954e-307, 9.34609790e-307],
       [8.45593934e-307, 9.34600963e-307, 1.86921143e-306,
        6.23061763e-307, 1.42421160e-306, 2.18569128e-312]])

In [28]:
identity = ny.identity(5) #give you identity matrix

In [29]:
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
identity.shape

(5, 5)

In [31]:
arr = ny.arange(99)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arr = arr.reshape(3,33) #divides and give you new array

In [34]:
arr = arr.ravel() #turns to one D- Array

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

#### ---------------NUMPY AXIS---------------

In [36]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [37]:
ar = ny.array(x)

In [38]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
ar.sum(axis=0) #deals with column

array([12, 15, 18])

In [43]:
ar.sum(axis=1) #deals with row

array([ 6, 15, 24])

###### ---------attributes------

In [45]:
ar.T # it will Transpose the Original Array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [46]:
ar. flat #give you an iterator

In [49]:
for i in ar.flat:
   print(i)

1
2
3
4
5
6
7
8
9


In [51]:
ar.ndim #gives you dimension of an array

2

In [53]:
ar.size # give you no. of elements

9

In [54]:
ar.nbytes #give you total bytes consumed by an ar

36

#### ---------methods----------

In [67]:
newArr = ny.array([33,76,543,98,71,9])

In [68]:
newArr.argmax() #gives you index of maximum element

2

In [69]:
newArr.argmin() #gives you index of minimum element

5

In [71]:
newArr.argsort() #inform you the elements's index which should be sort

array([5, 0, 4, 1, 3, 2], dtype=int64)

##### -----matrix operation-------

In [73]:
arr1 = ny.array([[1,2,3],[4,5,6],[7,8,9]])

In [74]:
arr2 = ny.array([[3,2,1],[6,4,3],[9,8,7]])

In [82]:
nArr = arr1 + arr2

In [83]:
nArr

array([[ 4,  4,  4],
       [10,  9,  9],
       [16, 16, 16]])

In [84]:
arr1 * arr2

array([[ 3,  4,  3],
       [24, 20, 18],
       [63, 64, 63]])

In [90]:
ny.sqrt(nArr)

array([[2.        , 2.        , 2.        ],
       [3.16227766, 3.        , 3.        ],
       [4.        , 4.        , 4.        ]])

##### Note: list, or other datatypes does'nt gives you 

In [91]:
[232,55] + [11,65] # it just apppend the elements not do addition operation

[232, 55, 11, 65]

In [94]:
ny.count_nonzero(nArr) #counting elements

9

In [95]:
import sys

#### checking which is optimistic

In [97]:
python_Array = [2,11,44,12,1]

In [98]:
numpy_Array  = ny.array(python_Array)

In [102]:
sys.getsizeof(1) * len(python_Array) # Array's one element size * 4   

140

In [103]:
numpy_Array.itemsize * numpy_Array.size # itemsize is an attribute

20